// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const _placeholder = 'REPLACE_ME';

  /// False when [firebase_options.dart] still has FlutterFire placeholder values.
  static bool get isConfigured =>
      android.projectId != _placeholder &&
      ios.projectId != _placeholder &&
      android.projectId.isNotEmpty;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4vdrPDR6K2iAG71sZ_ZVq8a93-Myc0lw',
    appId: '1:629984102803:web:7dfc0eb78eb9b95822c066',
    messagingSenderId: '629984102803',
    projectId: 'betafeedback-654e4',
    authDomain: 'betafeedback-654e4.firebaseapp.com',
    storageBucket: 'betafeedback-654e4.firebasestorage.app',
    measurementId: 'G-8CNKRTPZCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxHn3E7IhgvTNyD4K9j5fulx-mkLIs9o',
    appId: '1:629984102803:android:e673d0c3fde3808822c066',
    messagingSenderId: '629984102803',
    projectId: 'betafeedback-654e4',
    storageBucket: 'betafeedback-654e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkWGbSk3AG9xh4bhMSmEdo8TfDembYZg',
    appId: '1:629984102803:ios:8c229281c516c8b422c066',
    messagingSenderId: '629984102803',
    projectId: 'betafeedback-654e4',
    storageBucket: 'betafeedback-654e4.firebasestorage.app',
    androidClientId:
        '629984102803-34cer1r768vqkcjkb95o9jpib39icsl2.apps.googleusercontent.com',
    iosClientId:
        '629984102803-1oh04iq2pl15ialne81gos0m8vh4uavj.apps.googleusercontent.com',
    iosBundleId: 'com.betafeedback.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkWGbSk3AG9xh4bhMSmEdo8TfDembYZg',
    appId: '1:629984102803:ios:f5f72e25219dfe7222c066',
    messagingSenderId: '629984102803',
    projectId: 'betafeedback-654e4',
    storageBucket: 'betafeedback-654e4.firebasestorage.app',
    androidClientId:
        '629984102803-34cer1r768vqkcjkb95o9jpib39icsl2.apps.googleusercontent.com',
    iosClientId:
        '629984102803-me5jvli4nb8ksa5357tqii9dh2uao45e.apps.googleusercontent.com',
    iosBundleId: 'com.example.betafeedbackMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4vdrPDR6K2iAG71sZ_ZVq8a93-Myc0lw',
    appId: '1:629984102803:web:a0f45d8c9c88b6a922c066',
    messagingSenderId: '629984102803',
    projectId: 'betafeedback-654e4',
    authDomain: 'betafeedback-654e4.firebaseapp.com',
    storageBucket: 'betafeedback-654e4.firebasestorage.app',
    measurementId: 'G-PFZRD5N837',
  );
}
